import { DocsLayout, H2, H3, P, Lead, Code, CodeBlock, Callout, PageNav } from "@/components/docs/DocsLayout";

export const metadata = {
  title: "Build on Foundry — Foundry docs",
  description: "Integrate a Foundry Ingot into your product in under an hour.",
};

const toc = [
  { id: "audiences", label: "Pick your path" },
  { id: "integrator", label: "Path A · Call an Ingot" },
  { id: "smith", label: "Path B · Contribute to a Forge" },
  { id: "funder", label: "Path C · Open a Forge" },
  { id: "patterns", label: "Common patterns" },
];

export default function BuildOnFoundryDocsPage() {
  return (
    <DocsLayout
      active="/docs/build-on-foundry"
      eyebrow="Start here · Build on Foundry"
      title="From clean clone to shipping in under an hour."
      intro={
        <Lead>
          Three audiences, three paths. Pick the one that matches what
          you're trying to build today; the others are linked at the end
          of each path so you can come back when the time is right.
        </Lead>
      }
      toc={toc}
    >
      <H2 id="audiences">Pick your path</H2>
      <P>
        Foundry is a two-sided protocol — supply (Smiths, Funders) and
        demand (Builders). Most people land here as one of these three:
      </P>

      <ul className="text-body-lg space-y-3 text-platinum-300 ml-6 list-disc">
        <li><strong className="text-platinum-100">Path A · Call an Ingot</strong> — you ship product, you want a model. <em>Time: 15 minutes.</em></li>
        <li><strong className="text-platinum-100">Path B · Contribute to a Forge</strong> — you have data or compute, you want shares. <em>Time: 30 minutes.</em></li>
        <li><strong className="text-platinum-100">Path C · Open a Forge</strong> — you want a model to exist, you'll underwrite it. <em>Time: 1 hour.</em></li>
      </ul>

      <H2 id="integrator">Path A · Call an Ingot from your product</H2>

      <H3 id="A-1">1 · Browse the catalog</H3>
      <P>
        Pick an Ingot. Visit{" "}
        <a href="/forges" className="text-ember-400 hover:text-ember-300">/forges</a>{" "}
        to browse active Forges, or{" "}
        <a href="/lineage" className="text-ember-400 hover:text-ember-300">/lineage</a>{" "}
        to see the family tree of every minted Ingot. Copy the Ingot ID
        you want.
      </P>

      <H3 id="A-2">2 · Install + call</H3>
      <CodeBlock lang="bash">pnpm add @foundryprotocol/sdk</CodeBlock>
      <CodeBlock lang="ts">{`import { Foundry } from "@foundryprotocol/sdk";

const foundry = new Foundry({ contracts: "aristotle" });
const { output, receipt } = await foundry.inference.run(
  "ingot:0x…",
  { input: "Translate to Konkani: …" },
);`}</CodeBlock>

      <H3 id="A-3">3 · Display the receipt</H3>
      <P>
        Show your users that the model they're calling is co-owned, and
        that their use paid the co-owners. This is the trust-builder that
        differentiates a Foundry-backed product from any other LLM wrapper.
      </P>
      <CodeBlock lang="tsx">{`<div className="receipt">
  <span>Generated by <a href={\`/ingots/\${ingotId}\`}>Konkani v1</a></span>
  <span>•</span>
  <a href={\`https://aristotle.0g.explorer/tx/\${receipt.revenueTxHash}\`}>
    Revenue paid on-chain ↗
  </a>
</div>`}</CodeBlock>

      <Callout tone="ember">
        <p>
          Adapter for your framework? See <a href="/docs/adapters" className="text-ember-400 hover:text-ember-300">Adapters</a>.
          We ship Vercel AI SDK, LangChain, and OpenAI-compatible HTTP out of the box.
        </p>
      </Callout>

      <H2 id="smith">Path B · Contribute data or compute to a Forge</H2>

      <H3 id="B-1">1 · Find an open Forge</H3>
      <P>
        Forges in <Code>OPEN</Code> state accept contributions. The list
        is at{" "}
        <a href="/forges" className="text-ember-400 hover:text-ember-300">/forges</a>.
        Read the <Code>modelSpec</Code> to see what kind of data is wanted
        and the eval criteria.
      </P>

      <H3 id="B-2">2 · Submit your data</H3>
      <P>
        Upload your corpus to 0G Storage, get the storage root, then submit
        the root to the Forge:
      </P>
      <CodeBlock lang="ts">{`import { Foundry } from "@foundryprotocol/sdk";
import { createWalletClient, custom } from "viem";

const wallet  = createWalletClient({ transport: custom(window.ethereum) });
const foundry = new Foundry({ contracts: "aristotle", walletClient: wallet });

const { txHash } = await foundry.forge.contributeData(
  "forge:0x…",
  "0x<storageRoot>",
);`}</CodeBlock>

      <H3 id="B-3">3 · Wait for the Forge to close & claim</H3>
      <P>
        Once the contribution window ends, the eval coordinator runs LOO
        attribution. Shares mint automatically. When inference calls roll
        in, you pull your revenue with one line:
      </P>
      <CodeBlock lang="ts">{`const { txHash } = await foundry.revenue.claim(tokenId);`}</CodeBlock>

      <H2 id="funder">Path C · Open a Forge yourself</H2>

      <H3 id="C-1">1 · Write the specs</H3>
      <P>
        A Forge is defined by two specs:
      </P>
      <ul className="text-body-lg space-y-3 text-platinum-300 ml-6 list-disc">
        <li><strong className="text-platinum-100">modelSpec</strong> — the architecture, training recipe, hyperparameters, base model (if any). Stored on 0G Storage; hash committed on-chain.</li>
        <li><strong className="text-platinum-100">evalSpec</strong> — the held-out test set, the metric, the acceptance threshold. Stored on 0G Storage; hash committed on-chain.</li>
      </ul>

      <H3 id="C-2">2 · Pick an eval coordinator</H3>
      <P>
        Currently one coordinator runs: the Foundry-operated TEE on 0G
        Compute. Set its address in <Code>evalCoordinator</Code>. The
        roadmap includes opening this up to permissionless coordinators.
      </P>

      <H3 id="C-3">3 · Create the Forge</H3>
      <CodeBlock lang="ts">{`const { txHash } = await foundry.forge.create({
  modelSpec:               "0x<hashOfModelSpec>",
  evalSpec:                "0x<hashOfEvalSpec>",
  evalCoordinator:         "0x<coordinatorAddress>",
  contributionWindowEnds:  BigInt(Math.floor(Date.now()/1000) + 7*86400),
});`}</CodeBlock>

      <H3 id="C-4">4 · Fund + announce</H3>
      <P>
        Underwrite the compute budget by calling <Code>fundForge</Code>.
        Then announce the Forge — link to the explorer + the Forge detail
        page so Smiths can find it. The Forge in Public dashboard will
        surface it automatically once the indexer sees the create event.
      </P>

      <H2 id="patterns">Common patterns</H2>

      <H3 id="P-display">Display the cap table on your product</H3>
      <CodeBlock lang="tsx">{`const meta   = await foundry.ingot.meta(tokenId);
const shares = await Promise.all(
  holders.map(async (h) => ({
    holder: h,
    bps:    await foundry.ingot.shareOf(tokenId, h),
  })),
);
// Render a horizontal stacked bar segmented by share weight.`}</CodeBlock>

      <H3 id="P-attest">Show the TEE attestation</H3>
      <P>
        Every minted Ingot has its attestation indexed. Link to the
        explorer transaction for <Code>submitEvalResult</Code> from your
        UI; users can verify the TEE signature themselves.
      </P>

      <PageNav
        prev={{ href: "/docs/quickstart", label: "Quickstart" }}
        next={{ href: "/docs/attribution", label: "Verifiable attribution" }}
      />
    </DocsLayout>
  );
}
