/**
 * Archetype catalog for `create-foundry-app`.
 *
 * The five archetypes (A–E) mirror the builder segments in
 * `docs/0G-HACKATHON-INTEGRATION-PLAN.md` §2 — each leads with a different
 * value-prop and scaffolds a tailored, runnable `index.ts`. A sixth pseudo
 * archetype, `demo`, is the zero-setup one-command live-Ingot path: it targets
 * Galileo testnet, needs no key, and runs read-only inference against the
 * public demo Ingot.
 *
 * Archetype templates are the Foundry (ownership/revenue) path. The neutral
 * `@foundryprotocol/0gkit-*` quickstart lives behind `0g init` and the degit-able recipes in
 * `examples/` — see this package's README.
 */

/** The canonical public demo Ingot, used across the docs and the live demo. */
export const DEMO_INGOT = "ingot:0x8e2af4a000000000000000000000000000000001";

export type Network = "aristotle" | "galileo" | "local";

export type ArchetypeId = "A" | "B" | "C" | "D" | "E" | "demo";

export interface ArchetypeContext {
  /** Project directory name. */
  name: string;
  network: Network;
}

export interface Archetype {
  id: ArchetypeId;
  /** Short label shown in the CLI picker. */
  title: string;
  /** One-line lead value-prop (the §2 hook). */
  lead: string;
  /** Whether the generated project signs transactions (needs PRIVATE_KEY). */
  needsKey: boolean;
  /** Extra dependencies beyond the always-on base. */
  extraDeps?: Record<string, string>;
  /** Extra `.env.example` lines appended after the base block. */
  envLines: (ctx: ArchetypeContext) => string[];
  /** The README "What this template does" paragraph. */
  readmeBlurb: string;
  /** The generated, runnable `index.ts`. */
  index: (ctx: ArchetypeContext) => string;
}

const RPC_FOR = (n: Network): string =>
  n === "aristotle"
    ? "https://evmrpc.0g.ai"
    : n === "galileo"
      ? "https://evmrpc-testnet.0g.ai"
      : "http://127.0.0.1:8545";

/** Shared header every generated entrypoint opens with. */
const header = (title: string): string =>
  `// ${title}
// Generated by create-foundry-app. Docs: https://foundryprotocol.xyz/docs
import "dotenv/config";`;

const networkExpr =
  '(process.env.FOUNDRY_NETWORK as "aristotle" | "galileo" | "local") ?? "galileo"';

/* ───────────────────────── A — Agent infra / memory ─────────────────── */

const A: Archetype = {
  id: "A",
  title: "Agent infra / memory / identity",
  lead: "Your memory becomes equity — contribute memory logs to a Forge and co-own the model your agents improve.",
  needsKey: true,
  extraDeps: { ethers: "^6.13.0" },
  envLines: () => [
    "",
    "# Sovereign memory: where your agent's logs live before they become equity.",
    "ZG_STORAGE_INDEXER=https://indexer-storage.0g.network",
  ],
  readmeBlurb:
    "Persists an agent memory log to 0G Storage (sovereign — you keep the keys), then runs inference on a co-owned Ingot. Contributing that log to a Forge turns memory into an ownership share with no architecture change.",
  index: (ctx) => `${header("Archetype A — sovereign memory → co-owned model")}
import { Foundry, type IngotId } from "@foundryprotocol/sdk";
import { Wallet, JsonRpcProvider } from "ethers";

const network = ${networkExpr};
const rpcUrl = process.env.RPC_URL ?? "${RPC_FOR(ctx.network)}";
const ingotId = (process.env.INGOT_ID ?? "${DEMO_INGOT}") as IngotId;
const pk = process.env.PRIVATE_KEY;
if (!pk) throw new Error("set PRIVATE_KEY in .env to persist sovereign memory");

const foundry = new Foundry({ contracts: network, rpcUrl });

// 1) Sovereign memory: store an agent log to 0G Storage. You hold the signer.
const signer = new Wallet(pk, new JsonRpcProvider(rpcUrl));
const memory = {
  agent: "${ctx.name}",
  ts: new Date().toISOString(),
  episodes: [{ prompt: "Who am I?", recall: "a sovereign agent" }],
};
const { rootHash } = await foundry.storage.uploadJson(memory, { signer });
console.log("memory persisted → 0G Storage root:", rootHash);

// 2) Reason over a co-owned Ingot. Contribute \`rootHash\` to a Forge later to
//    turn this memory into an ownership share (see foundry.forge.contributeData).
const { output, receipt } = await foundry.inference.run(ingotId, {
  input: "Summarise my last episode.",
});
console.log("output:", output);
console.log("receipt:", receipt);
`,
};

/* ─────────────────── B — Verifiable finance / DeFi agents ───────────── */

const B: Archetype = {
  id: "B",
  title: "Verifiable finance / trading / DeFi",
  lead: "TEE-attested inference with an on-chain receipt for every decision — the audit trail judges love.",
  needsKey: false,
  envLines: () => [],
  readmeBlurb:
    "Runs a reasoning call and prints the on-chain inference receipt (`inferenceTxHash`) — a verifiable audit trail you can store alongside every trade. No key needed to read; sign later to settle revenue.",
  index: (ctx) => `${header("Archetype B — verifiable inference + on-chain receipt")}
import { Foundry, type IngotId } from "@foundryprotocol/sdk";

const network = ${networkExpr};
const rpcUrl = process.env.RPC_URL ?? "${RPC_FOR(ctx.network)}";
const ingotId = (process.env.INGOT_ID ?? "${DEMO_INGOT}") as IngotId;

const foundry = new Foundry({ contracts: network, rpcUrl });

const decision = await foundry.inference.run(ingotId, {
  input: "Risk-rate this position: long ETH 3x. Reply LOW/MED/HIGH + one line.",
});

// Store \`receipt\` next to the trade. \`inferenceTxHash\` is the verifiable,
// on-chain proof that this exact reasoning produced this exact decision.
console.log("decision:", decision.output);
console.log("requestId:", decision.receipt.requestId);
console.log("inferenceTxHash:", decision.receipt.inferenceTxHash ?? "(pending)");
console.log("latencyMs:", decision.receipt.latencyMs);
`,
};

/* ───────────── C — Marketplaces / skill / gig / payment ─────────────── */

const C: Archetype = {
  id: "C",
  title: "Marketplaces / skill / gig / payment",
  lead: "Every inference on an Ingot you co-own pays you passively — a built-in revenue rail for your marketplace.",
  needsKey: true,
  envLines: () => [
    "",
    "# tokenId of the Ingot SKU you co-own (revenue accrues to holders).",
    "INGOT_TOKEN_ID=1",
  ],
  readmeBlurb:
    "Treats an Ingot as a first-class model SKU: runs inference, then reads claimable revenue and claims it via the RevenueSplitter — payout accounting you get for free.",
  index: (ctx) => `${header("Archetype C — Ingot as a paying model SKU")}
import { Foundry, createWalletClient, http, type Hex, type IngotId } from "@foundryprotocol/sdk";
import { privateKeyToAccount } from "viem/accounts";

const network = ${networkExpr};
const rpcUrl = process.env.RPC_URL ?? "${RPC_FOR(ctx.network)}";
const ingotId = (process.env.INGOT_ID ?? "${DEMO_INGOT}") as IngotId;
const tokenId = BigInt(process.env.INGOT_TOKEN_ID ?? "1");
const pk = process.env.PRIVATE_KEY as Hex | undefined;
if (!pk) throw new Error("set PRIVATE_KEY in .env to claim marketplace revenue");

const account = privateKeyToAccount(pk);
const walletClient = createWalletClient({ account, transport: http(rpcUrl) });
const foundry = new Foundry({ contracts: network, rpcUrl, walletClient });

// 1) A buyer runs the SKU.
const { output } = await foundry.inference.run(ingotId, { input: "Quote me." });
console.log("SKU output:", output);

// 2) You're a co-owner — revenue accrued. Check, then claim it.
const claimable = await foundry.revenue.claimable(tokenId, account.address);
console.log("claimable:", claimable, "wei");
if (claimable > 0n) {
  const { txHash } = await foundry.revenue.claim(tokenId);
  console.log("claimed → tx:", txHash);
}
`,
};

/* ─────────────────── D — Consumer / RWA / tools ─────────────────────── */

const D: Archetype = {
  id: "D",
  title: "Consumer / RWA / tools",
  lead: "Drop in a co-owned model instantly — an HTTP endpoint, no web3 code needed to start.",
  needsKey: false,
  envLines: () => ["", "# Port for the local HTTP adapter.", "PORT=8787"],
  readmeBlurb:
    "Exposes a co-owned Ingot behind a plain HTTP endpoint (`POST /infer`) — your consumer app calls it like any API. Zero web3 code on the caller side; contribute domain data later to earn from the intelligence layer.",
  index: (
    ctx
  ) => `${header("Archetype D — co-owned model behind a plain HTTP endpoint")}
import { createServer } from "node:http";
import { Foundry, type IngotId } from "@foundryprotocol/sdk";

const network = ${networkExpr};
const rpcUrl = process.env.RPC_URL ?? "${RPC_FOR(ctx.network)}";
const ingotId = (process.env.INGOT_ID ?? "${DEMO_INGOT}") as IngotId;
const port = Number(process.env.PORT ?? "8787");

const foundry = new Foundry({ contracts: network, rpcUrl });

const server = createServer(async (req, res) => {
  if (req.method !== "POST" || req.url !== "/infer") {
    res.writeHead(404).end("POST /infer { input }");
    return;
  }
  let body = "";
  for await (const chunk of req) body += chunk;
  try {
    const { input } = JSON.parse(body || "{}");
    const { output, receipt } = await foundry.inference.run(ingotId, {
      input: String(input ?? "Hello"),
    });
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ output, receipt }));
  } catch (err) {
    res.writeHead(500).end(String(err));
  }
});

server.listen(port, () => {
  console.log(\`co-owned model live → curl -XPOST localhost:\${port}/infer -d '{"input":"Hi"}'\`);
});
`,
};

/* ─────────────────── E — Pure infra / data / compute ────────────────── */

const E: Archetype = {
  id: "E",
  title: "Pure infra / data / compute",
  lead: "You already produce the inputs Forges need — become a contributor and earn Ingot shares for infra you run.",
  needsKey: true,
  extraDeps: { ethers: "^6.13.0" },
  envLines: () => [
    "",
    "# Forge you're contributing infra/data to (earns you Ingot shares).",
    "FORGE_ID=forge:0x0000000000000000000000000000000000000000",
    "ZG_STORAGE_INDEXER=https://indexer-storage.0g.network",
  ],
  readmeBlurb:
    "Publishes a dataset/compute artifact to 0G Storage and contributes it to a Forge — the infra you already run becomes an ownership stake in the resulting Ingot.",
  index: (ctx) => `${header("Archetype E — contribute infra/data → earn Ingot shares")}
import { Foundry, type ForgeId } from "@foundryprotocol/sdk";
import { Wallet, JsonRpcProvider } from "ethers";

const network = ${networkExpr};
const rpcUrl = process.env.RPC_URL ?? "${RPC_FOR(ctx.network)}";
const forgeId = (process.env.FORGE_ID ?? "") as ForgeId;
const pk = process.env.PRIVATE_KEY;
if (!pk) throw new Error("set PRIVATE_KEY in .env to contribute");
if (!forgeId.startsWith("forge:0x")) {
  throw new Error("set FORGE_ID in .env to the Forge you're contributing to");
}

const foundry = new Foundry({ contracts: network, rpcUrl });
const signer = new Wallet(pk, new JsonRpcProvider(rpcUrl));

// 1) Publish the artifact your infra already produces.
const { rootHash } = await foundry.storage.uploadJson(
  { kind: "dataset", source: "${ctx.name}", rows: ["sample-a", "sample-b"] },
  { signer }
);
console.log("artifact published → root:", rootHash);

// 2) Contribute it to the Forge — this is the on-chain ownership claim.
const { txHash } = await foundry.forge.contributeData(forgeId, rootHash);
console.log("contribution tx:", txHash, "→ you now hold a share of the Ingot");
`,
};

/* ─────────────────────────── demo (zero-setup) ──────────────────────── */

const DEMO: Archetype = {
  id: "demo",
  title: "Live demo (zero setup)",
  lead: "One command, real testnet inference against the public demo Ingot — no key, no funds.",
  needsKey: false,
  envLines: () => [],
  readmeBlurb:
    "The zero-setup live demo: `npm run demo` runs read-only inference against the public demo Ingot on Galileo testnet. No PRIVATE_KEY, no funds — proof the toolkit works in one command.",
  index: () => `${header("Live demo — zero-setup inference on Galileo testnet")}
import { Foundry, type IngotId } from "@foundryprotocol/sdk";

// Galileo testnet, public demo Ingot, no key required.
const foundry = new Foundry({
  contracts: "galileo",
  rpcUrl: "${RPC_FOR("galileo")}",
});

const ingotId = "${DEMO_INGOT}" as IngotId;
const { output, receipt } = await foundry.inference.run(ingotId, {
  input: "Say hello from the Foundry live demo.",
});

console.log("ingot:  ", ingotId);
console.log("output: ", output);
console.log("receipt:", receipt);
console.log("\\n✓ live demo complete — you just called a co-owned model on 0G.");
`,
};

export const ARCHETYPES: Record<ArchetypeId, Archetype> = {
  A,
  B,
  C,
  D,
  E,
  demo: DEMO,
};

export const ARCHETYPE_ORDER: ArchetypeId[] = ["A", "B", "C", "D", "E", "demo"];

export function getArchetype(id: string): Archetype {
  const a = ARCHETYPES[id as ArchetypeId];
  if (!a) {
    throw new Error(
      `unknown archetype '${id}' (expected one of ${ARCHETYPE_ORDER.join(", ")})`
    );
  }
  return a;
}

export { RPC_FOR };
